export const Top5entidades = [
    {
        id:1,
        localidad: "Vicente López",
        nombre:"Roberto",
        apellido:"Gomez",
        entidad:"especialista",
        direccion:"Avenida Las Heras 225 3A",
        rating:"5",
        especialidad:"Traumatología",
    },
    {
        id:2,
        localidad:"Florida",
        nombre:"Roberta",
        apellido:"Gomez",
        entidad:"especialista",
        direccion:"Avenida Las Heras 224 3A",
        rating:"3",
        especialidad:"Odontología",
    },
    {
        id:3,
        localidad:"Villa Martelli",
        nombre:"Mario",
        apellido:"Gomez",
        entidad:"especialista",
        direccion:"Avenida Las Heras 222 3A",
        rating:"5",
        especialidad:"Pediatría",
    },
    {
        id:4,
        localidad:"Florida Oeste",
        nombre:"Maria",
        apellido:"Gomez",
        entidad:"especialista",
        direccion:"Avenida Las Heras 221 3A",
        rating:"4",
        especialidad:"Kinesiología",
    },
    {
        id:5,
        localidad:"Villa Ballester",
        nombre:"Ramiro",
        apellido:"Gomez",
        entidad:"especialista",
        direccion:"Avenida Las Heras 220 3A",
        rating:"4",
        especialidad:"Psicología",
    },
]