import imagen from "./assets/person-icon.png";
export const Top5entidades = [
    {
        id:1,
        localidad: "Vicente López",
        nombre:"Roberto",
        apellido:"Gomez",
        entidad:"Profesional",
        direccion:"Avenida Las Heras 225",
        piso:"3A",
        telefono:"4877-6988",
        mail:"robertogomez@gmail.com",
        matricula:"96967",
        rating:"5",
        especialidad:"Traumatología",
        image: "https://i.ibb.co/4Wb0SgG/Traumatologia.jpg",
    },
    {
        id:2,
        localidad:"Florida",
        nombre:"Mariela",
        apellido:"Fernandez",
        entidad:"Profesional",
        direccion:"Pichincha 201",
        piso:"1A",
        telefono:"4877-7875",
        mail:"fernandezmar@gmail.com",
        matricula:"96968",
        rating:"5",
        especialidad:"Odontología",
        image: imagen,
    },
    {
        id:3,
        localidad:"Villa Martelli",
        nombre:"Mario",
        apellido:"Scogla",
        entidad:"Profesional",
        direccion:"General Juan Lavalle 4457",
        piso:"2C",
        telefono:"4547-6928",
        mail:"mariopedriatria@gmail.com",
        matricula:"96969",
        rating:"5",
        especialidad:"Pediatría",
        image: "https://i.ibb.co/V0GGGb5/6-cosas-que-ningun-doctor-puede-hacerte-3.jpg"
    },
    {
        id:4,
        localidad:"Florida Oeste",
        nombre:"Maria",
        apellido:"Benitez",
        entidad:"Profesional",
        direccion:"Avenida Córdoba 441",
        piso:"4",
        telefono:"4457-6918",
        mail:"benitezmaria@gmail.com",
        matricula:"96970",
        rating:"5",
        especialidad:"Kinesiología",
        image: imagen,
    },
    {
        id:5,
        localidad:"Villa Ballester",
        nombre:"Ramiro",
        apellido:"Hudson",
        entidad:"Profesional",
        direccion:"Artigas 5563",
        piso:"8D",
        telefono:"4547-6666",
        mail:"ramirohud@hotmail.com",
        matricula:"96971",
        rating:"4",
        especialidad:"Psicología",
        image: imagen,
    },
]